### ISSUE TITLE
Cannot run downloaded binary on Ubuntu 20.04

### ISSUE THREAD

**Issue by kumarshantanu** [bowbahdoe/jresolve-cli#1]
I ran into the following after I tried the first binary download on AMD64 Ubuntu 20.04:

```shell
$ jresolve pkg:maven/org.apache.commons/commons-collections4@4.4
jresolve: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by jresolve)
jresolve: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by jresolve)
```

However, when I built it locally with `just exe` (GraalVM-ce-21) it worked fine.

**Comment by bowbahdoe** [comment]
This is [solved now](https://clojurians.slack.com/archives/C06MAR553/p1699638836685669?thread_ts=1699553120.034759&cid=C06MAR553)
